### ISSUE TITLE
[Bug Report] Does not work for non-English system username

### ISSUE THREAD

**Issue by suxiaolei97** [SpriteOvO/AirPodsDesktop#14]
I have already download and install the AirPodsDesktop-0.3.0-win32.exe, then I try to run it, but it doesn't work on my computer.
It seems like that this application can't work on computer which Users folder's name in non-English languages.
The window notice:

AirPodsDesktop fatal error
------------------------------
An error has occurred!
Please help us fix this problem.
spdlog initialize failed.
Failed opening file C:/Users/璋鄧繆鐓?
AppData/Local/AirPodsDesktop/AirPodsDesktop.log for
writing: legal byte sequence
------------------------------
Click "Yes" will pop up GitHub issue tracker page.
You can submit this information to us there.
Thank you very much.

**Comment by SpriteOvO** [comment]
Thanks for your bug report!
I have committed a fix, could you try it after the [CI compilation](https://github.com/SpriteOvO/AirPodsDesktop/actions/runs/1521794900) is done?

**Comment by SpriteOvO** [comment]
* Forced push to edit the commit message just now

**Comment by suxiaolei97** [comment]
Yes! It works well in this version. Thank you to your work! 
Long live to open source spirit.
This application is amazing! I feel surprise to its completeness.
But still not perfect in animation window, I'm not sure that is a bug or not,
because animation window display the bluetooth address instead my airpods name.

**Comment by suxiaolei97** [comment]
emmm,
I disconnet my airpods2 and connect again.
It shows airpods name correctly. 
Now I hope this application will be better!
Animation Window do not have continuous curvature, and hope author to add anti-aliasing effect feature.

**Comment by SpriteOvO** [comment]
I have opened a new issue #15 to explain the incorrect device name problem and am ready to implement a mitigation.
You can get details about anti-aliasing in the corners of windows in issue #13.
This issue will be closed. Thanks for your appreciation!
